version: '3.5'
services:
  app:
    image: ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}
    command: ["gunicorn", "-b", "0.0.0.0:5000", "-w", "5", "app:app", "--access-logfile=-", "--error-logfile=-", "--preload"]
    ports:
      - "5000:5000"
    environment:
      BUILDKITE_API_BASE_URL: ${BUILDKITE_API_BASE_URL}
      BUILDKITE_API_TOKEN: ${BUILDKITE_API_TOKEN}
      BUILDKITE_ORG: ${BUILDKITE_ORG}
      CONBENCH_URL: ${CONBENCH_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_HOST: ${DB_HOST}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      DB_PORT: ${DB_PORT}
      FLASK_DEBUG: 0
      GITHUB_API_BASE_URL: ${GITHUB_API_BASE_URL}
      GITHUB_REPO: ${GITHUB_REPO}
      GITHUB_REPO_WITH_BENCHMARKABLE_COMMITS: ${GITHUB_REPO_WITH_BENCHMARKABLE_COMMITS}
      MAX_COMMITS_TO_FETCH: ${MAX_COMMITS_TO_FETCH}
      PIPY_API_BASE_URL: ${PIPY_API_BASE_URL}
      PIPY_PROJECT: ${PIPY_PROJECT}
      SLACK_API_BASE_URL: ${SLACK_API_BASE_URL}
      SLACK_API_TOKEN: ${SLACK_API_TOKEN}
      SLACK_CHANNEL_FOR_BENCHMARK_RESULTS: ${SLACK_CHANNEL_FOR_BENCHMARK_RESULTS}
      SLACK_USER_ID_FOR_WARNINGS: ${SLACK_USER_ID_FOR_WARNINGS}
