steps:
  - label: "Build & Push"
    key: "build-and-push"
    concurrency: 1
    concurrency_group: "arrow-bci-deploy"
    command:
      - docker build -t ${FLASK_APP} .
      - docker tag ${FLASK_APP}:latest ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
      - docker push ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}

  - label: "Run Migrations"
    key: "run-migrations"
    depends_on: "build-and-push"
    concurrency: 1
    concurrency_group: "arrow-bci-deploy"
    command:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
      - docker pull ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}
      - docker-compose -f envs/prod/docker-compose.yml run app alembic upgrade head

  - label: "Deploy secrets and config"
    key: "deploy-secrets-and-config"
    depends_on: "run-migrations"
    concurrency: 1
    concurrency_group: "arrow-bci-deploy"
    command: |
      aws eks --region us-east-2 update-kubeconfig --name ${EKS_CLUSTER}
      kubectl config set-context --current --namespace=${NAMESPACE}
      cat envs/prod/secrets.yml | sed "\
        s/{{BUILDKITE_API_TOKEN}}/$(echo -n $BUILDKITE_API_TOKEN | base64 -w 0)/g;\
        s/{{DB_HOST}}/$(echo -n $DB_HOST | base64 -w 0)/g;\
        s/{{DB_NAME}}/$(echo -n $DB_NAME | base64 -w 0)/g;\
        s/{{DB_PASSWORD}}/$(echo -n $DB_PASSWORD | base64 -w 0)/g;\
        s/{{DB_USERNAME}}/$(echo -n $DB_USERNAME | base64 -w 0)/g;\
        s/{{GITHUB_API_TOKEN}}/$(echo -n $GITHUB_API_TOKEN | base64 -w 0)/g;\
        s/{{GITHUB_SECRET}}/$(echo -n $GITHUB_SECRET | base64 -w 0)/g;\
        s/{{SLACK_API_TOKEN}}/$(echo -n $SLACK_API_TOKEN | base64 -w 0)/g;\
        s/{{SLACK_CHANNEL_FOR_BENCHMARK_RESULTS}}/$(echo -n $SLACK_CHANNEL_FOR_BENCHMARK_RESULTS | base64 -w 0)/g;\
        s/{{SLACK_USER_ID_FOR_WARNINGS}}/$(echo -n $SLACK_USER_ID_FOR_WARNINGS | base64 -w 0)/g" | kubectl apply -f -
      cat envs_prod_config.yml | sed "\
        s_{{BUILDKITE_API_BASE_URL}}_${BUILDKITE_API_BASE_URL}_g;\
        s_{{BUILDKITE_ORG}}_${BUILDKITE_ORG}_g;\
        s_{{CONBENCH_URL}}_${CONBENCH_URL}_g;\
        s_{{DB_PORT}}_${DB_PORT}_g;\
        s_{{ENV}}_${ENV}_g;\
        s_{{FLASK_APP}}_${FLASK_APP}_g;\
        s_{{GITHUB_API_BASE_URL}}_${GITHUB_API_BASE_URL}_g;\
        s_{{GITHUB_REPO}}_${GITHUB_REPO}_g;\
        s_{{GITHUB_REPO_WITH_BENCHMARKABLE_COMMITS}}_${GITHUB_REPO_WITH_BENCHMARKABLE_COMMITS}_g;\
        s_{{MAX_COMMITS_TO_FETCH}}_${MAX_COMMITS_TO_FETCH}_g;\
        s_{{PIPY_API_BASE_URL}}_${PIPY_API_BASE_URL}_g;\
        s_{{PIPY_PROJECT}}_${PIPY_PROJECT}_g;\
        s_{{SLACK_API_BASE_URL}}_${SLACK_API_BASE_URL}_g" | kubectl apply -f -

  - label: "Deploy CI API Server"
    key: "deploy-ci-api-server"
    depends_on: "deploy-secrets-and-config"
    concurrency: 1
    concurrency_group: "arrow-bci-deploy"
    command:
      - echo "WIP"

  - label: "Update Machine Configs"
    key: "update-machine-configs"
    depends_on: "deploy-ci-api-server"
    concurrency: 1
    concurrency_group: "arrow-bci-deploy"
    command:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
      - docker pull ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}
      - docker-compose -f envs/prod/docker-compose.yml run app python -c 'from buildkite.deploy.update_machine_configs import update_machine_configs; update_machine_configs()'
