steps:
  - label: "Build & Push"
    key: "build-and-push"
    concurrency: 1
    concurrency_group: "arrow-bci-deploy"
    command:
      - docker build -t ${FLASK_APP} .
      - docker tag ${FLASK_APP}:latest ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
      - docker push ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}

  - wait

  - label: "Other Steps"
    command:
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin ${DOCKER_REGISTRY}
      - docker pull ${DOCKER_REGISTRY}/${FLASK_APP}:${BUILDKITE_COMMIT}
      - docker-compose -f buildkite/schedule_and_publish/docker-compose.yml run app alembic upgrade head
      - docker-compose -f buildkite/schedule_and_publish/docker-compose.yml run app python -c 'from buildkite.schedule_and_publish.get_commits import get_commits; get_commits()'
