steps:
  - label: "Run Benchmarks"
    command: source buildkite/benchmark/utils.sh build_arrow_and_run_benchmark_groups
    timeout_in_minutes: 120
    retry:
      automatic:
        - exit_status: -1
          limit: 2
        - exit_status: 143
          limit: 2
        - exit_status: 255
          limit: 2
